### ISSUE TITLE
add base iamge and merge image crash   (MI 4C  Android4.4.4KTU84P)

### ISSUE THREAD

**Issue by philos3** [cooltechworks/BitmapMerger#3]
05-02 18:43:52.065 26674-26983/com.cooltechworks.bitmapmerger E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                                Process: com.cooltechworks.bitmapmerger, PID: 26674
                                                                                java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                    at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:841)
                                                                                 Caused by: com.cooltechworks.bitmapmerger.tasks.BitmapDecoderTask$BitmapDecodeException: Did not provide a valid Uri.
                                                                                    at com.cooltechworks.bitmapmerger.tasks.BitmapDecoderTask.decodeSampledBitmapFromDisk(BitmapDecoderTask.java:181)
                                                                                    at com.cooltechworks.bitmapmerger.tasks.BitmapDecoderTask.doInBackground(BitmapDecoderTask.java:126)
                                                                                    at com.cooltechworks.bitmapmerger.tasks.BitmapDecoderTask.doInBackground(BitmapDecoderTask.java:25)
                                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                    at java.lang.Thread.run(Thread.java:841)

**Comment by sharish** [comment]
Can you post the code you have used which caused this crash. As you can see the source [BitmapDecoderTask.java](https://github.com/cooltechworks/BitmapMerger/blob/master/app/src/main/java/com/cooltechworks/bitmapmerger/tasks/BitmapDecoderTask.java) line 181, the URI you have fetched resulted in FileNotFoundException aborting the process. Check whether the image URI reference have a valid file path.

Thanks,
Harish

**Comment by philos3** [comment]
I just download the zip ,unzip it and run the code without checking
I'm so sorry,I forgot to add the permission   android.permission.WRITE_EXTERNAL_STORAGE
now the problem has been solved

**Comment by sharish** [comment]
Fine then.
